# This is a basic workflow to help you get started with Actions

name: ConditionCheck

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Branch Name
        run: echo $GITHUB_REF_NAME
      - name: Checks Branch master
        if: contains('$GITHUB_REF_NAME', 'master')
        run: echo Branch is master
      
      - name: Checks Branch dev
        if: contains('$GITHUB_REF_NAME', 'dev')
        run: echo Branch is dev
