# This is a basic workflow to help you get started with Actions ..
name: CI
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run deployment against'
        type: choice
        required: true
        options: [DEV, PRE, PROD]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment
    environment: ${{ github.event.inputs.environment }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "Creating file with secret .."
          touch ${{ secrets.AWS_ROLE }}
      - name: Running ls command
        run: ls
