# This is a basic workflow to help you get started with Actions ...
name: CI
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run deployment against'
        type: choice
        required: true
        options: [DEV, PRE, PROD]        

permissions:
  id-token: write
  contents: read

env:
  AWS_PROFILE_NAME: CDF-DEVOPS-${{ github.event.inputs.environment }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment
    environment: ${{ github.event.inputs.environment }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-1
          role-session-name: GithubActions
          
      - name: Validate Caller Identity
        run: |
          aws sts get-caller-identity
          
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $AWS_PROFILE_NAME
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $AWS_PROFILE_NAME
          aws configure set aws_session_token $AWS_SESSION_TOKEN --profile $AWS_PROFILE_NAME
          
      - name: Listing Code Build Projects
        run: |
          aws codebuild list-projects --profile $AWS_PROFILE_NAME
